// The service worker's source, generated at build time by `serviceWorker()` in `./vite.ts`.
//
// Internal: not an export of the package. It is a plain function from a config to the text of
// `sw.js`, so `tools/verify-pwa.ts` can run the very same worker against fake `caches` and
// `fetch` in bun. The worker itself is plain JavaScript in a template (it runs in the browser's
// service worker global scope, not through any bundler), so keep it small and ES2020.
//
// Strategy, generalised from demolition-shot's hand-written `sw.js`:
// - install: fetch the precache list into the build's cache, then take over at once;
// - activate: delete this app's caches of older builds (never another app's on the origin);
// - navigations: network first (a new deploy shows up at once), the cached page offline;
// - runtime rules (fetched data): their own strategy, in a cache that outlives builds;
// - precached files and hashed build assets: cache first;
// - anything else in scope (icons, the manifest): stale-while-revalidate.

/** How a runtime rule answers a request. */
export type CacheStrategy = "cache-first" | "network-first" | "stale-while-revalidate";

/** A runtime rule as it is baked into the worker: a path prefix, or a RegExp's parts. */
export interface BakedRule {
  prefix?: string;
  source?: string;
  flags?: string;
  strategy: CacheStrategy;
}

/** Everything the worker needs, fixed at build time. */
export interface BakedConfig {
  /** Cache name prefix, unique per app on the origin. */
  name: string;
  /** Build id: names the build's cache, so each deploy gets a fresh one. */
  build: string;
  /** Files to fetch on install, relative to the scope (`"assets/index-abc.js"`, `"world/index.html"`). */
  precache: string[];
  /** Prefix of hashed build assets, relative to the scope (`"assets/"`). */
  assets: string;
  /** The worker's own file, relative to the scope; never cached. */
  file: string;
  /** Runtime rules, first match wins. */
  runtime: BakedRule[];
}

/** The cache holding one build's files. */
export const buildCacheName = (name: string, build: string): string => `${name}-${build}`;
/** The cache holding runtime-rule responses; it survives deploys. */
export const runtimeCacheName = (name: string): string => `${name}-runtime-cache`;

/** A build id: a short base-36 hash (cyrb53) of the given parts, so equal builds get equal ids. */
export function hashBuild(parts: Iterable<string | Uint8Array>): string {
  let h1 = 0xdeadbeef, h2 = 0x41c6ce57;
  const mix = (c: number) => {
    h1 = Math.imul(h1 ^ c, 2654435761);
    h2 = Math.imul(h2 ^ c, 1597334677);
  };
  for (const part of parts) {
    if (typeof part === "string") for (let i = 0; i < part.length; i++) mix(part.charCodeAt(i));
    else for (let i = 0; i < part.length; i++) mix(part[i]);
    mix(0x1f); // separator, so ["ab", "c"] and ["a", "bc"] differ
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507) ^ Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507) ^ Math.imul(h1 ^ (h1 >>> 13), 3266489909);
  return (4294967296 * (2097151 & h2) + (h1 >>> 0)).toString(36);
}

/** The text of `sw.js` for a config. */
export function serviceWorkerSource(config: BakedConfig): string {
  return `// Generated by serviceWorker() from @voxolith/engine/vite. Do not edit; rebuild instead.
const C = ${JSON.stringify(config)};
${WORKER}`;
}

const WORKER = String.raw`const SCOPE = self.registration.scope; // always ends with /
const SCOPE_PATH = new URL(SCOPE).pathname;
const CACHE = C.name + "-" + C.build;
const RUNTIME = C.name + "-runtime-cache";
// This app's build caches: its name, a dash, a base-36 id. Another app's names never match,
// even one whose name starts with ours ("demo" and "demo-shot-x": the rest has a dash).
const OLD = new RegExp("^" + C.name.replace(/[.*+?^$\{\}()|[\]\\]/g, "\\$&") + "-[0-9a-z]+$");
const RULES = C.runtime.map((r) => {
  const re = r.prefix === undefined ? new RegExp(r.source, r.flags) : null;
  return { test: (p) => (re ? re.test(p) : p.startsWith(r.prefix)), strategy: r.strategy };
});
const at = (file) => new URL(file, SCOPE).href;
const PRECACHE = new Set(C.precache.map(at));
// A page's cache key: no query or hash, and a directory means its index.html.
const pageKey = (href) => {
  const u = new URL(href);
  u.search = "";
  u.hash = "";
  if (u.pathname.endsWith("/")) u.pathname += "index.html";
  return u.href;
};
const keep = (res) => res && res.status === 200;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      Promise.all(
        [...PRECACHE].map((href) =>
          fetch(new Request(href, { cache: "reload" }))
            .then((res) => (keep(res) ? cache.put(href, res) : undefined))
            .catch(() => undefined),
        ),
      ),
    ).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && OLD.test(k)).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

function store(event, name, key, res) {
  if (!keep(res)) return;
  const copy = res.clone();
  event.waitUntil(caches.open(name).then((c) => c.put(key, copy)).catch(() => undefined));
}

// Offline (fetch throws) or a server error: the cached copy if there is one.
async function networkFirst(event, name, key) {
  let res;
  try {
    res = await fetch(event.request);
  } catch (err) {
    const hit = await (await caches.open(name)).match(key);
    if (hit) return hit;
    throw err;
  }
  if (res.status >= 500) return (await (await caches.open(name)).match(key)) || res;
  store(event, name, key, res);
  return res;
}

async function cacheFirst(event, name, key) {
  const hit = await (await caches.open(name)).match(key);
  if (hit) return hit;
  const res = await fetch(event.request);
  store(event, name, key, res);
  return res;
}

async function staleWhileRevalidate(event, name, key) {
  const hit = await (await caches.open(name)).match(key);
  const network = fetch(event.request).then((res) => {
    store(event, name, key, res);
    return res;
  });
  if (!hit) return network;
  event.waitUntil(network.catch(() => undefined));
  return hit;
}

const STRATEGY = { "cache-first": cacheFirst, "network-first": networkFirst, "stale-while-revalidate": staleWhileRevalidate };

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET" || req.headers.has("range")) return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(SCOPE_PATH)) return;
  const rel = url.pathname.slice(SCOPE_PATH.length);
  if (rel === C.file) return;
  if (req.mode === "navigate") {
    event.respondWith(networkFirst(event, CACHE, pageKey(req.url)));
    return;
  }
  const rule = RULES.find((r) => r.test(rel));
  if (rule) {
    event.respondWith(STRATEGY[rule.strategy](event, RUNTIME, req.url));
    return;
  }
  const bare = url.origin + url.pathname;
  if (PRECACHE.has(bare) || rel.startsWith(C.assets)) {
    event.respondWith(cacheFirst(event, CACHE, url.search ? req.url : bare));
    return;
  }
  event.respondWith(staleWhileRevalidate(event, CACHE, req.url));
});
`;
